### ISSUE TITLE
If i have a locally installed zenn-cli, please use it

### ISSUE THREAD

**Issue by ytoune** [negokaz/vscode-zenn-editor#1]
[zenn-cli のインストール手順](https://zenn.dev/zenn/articles/install-zenn-cli) には  
`npm install -g zenn-cli` ではなく `npm install zenn-cli` と書かれています  
プロジェクト内にインストールされた zenn-cli があればそちらを使うようにしてほしいです

**Comment by ytoune** [comment]
`require.resolve('zenn-cli/bin/zenn', { paths: [workingDirectory.fsPath] })` が動けば楽そうですが…  
私の環境では動きませんでした  
下記なら一応動きそうです  

```ts
const envpath = path.join(workingDirectory.fsPath, 'node_modules', '.bin') + path.delimiter + process.env.PATH;
return vscode.Uri.file(await which('zenn', { path: envpath }));
```

**Comment by negokaz** [comment]
@ytoune 
ご報告ありがとうございます！
確かに `npm install zenn-cli` だけで動くようになったほうがわかりやすくて良いですね。

一応、現状では次のように環境変数 `PATH` を設定すると、グローバルに zenn-cli をインストールしていない環境でも利用できるはずです。

```bash
export PATH="$(npm bin):${PATH}"
# or
export PATH="node_modules/.bin:${PATH}"
```

**Comment by negokaz** [comment]
@ytoune 
先ほど `node_modules/.bin` を見るように対応を行ったバージョン `0.2.0` をリリースしました！お時間あるときにご確認頂けると幸いです。
