### ISSUE TITLE
プレビューが表示されない (が別のファイルを開いてから再度開くと表示される)

### ISSUE THREAD

**Issue by susumuota** [negokaz/vscode-zenn-editor#23]
以下バージョンの VSCode - Insiders を使っています。
```
Version: 1.56.0-insider (Universal)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T21:55:28.605Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 19.6.0
```

記事を開いて、右上の `Zenn Editor: Open Preview` ボタンを押すと `Zenn Editor Preview` のエリアが表示されるのですが、以下のように真っ白な画面でした。

![image](https://user-images.githubusercontent.com/1632335/117097806-a38cf600-ada7-11eb-9521-447bdc834cf8.png)

その後、別のファイル(例えば `.gitignore`)を開いてから再度該当記事をクリックするとプレビューが表示されました。

![image](https://user-images.githubusercontent.com/1632335/117098081-69702400-ada8-11eb-9938-49a83c4a7cf8.png)

VSCode は最近使い始めたところで Extensions のログの表示方法が分からないのですが、もし手がかり等ありましたら教えて下さい。

**Comment by negokaz** [comment]
@susumuota 問題のご報告ありがとうございます。

プレビューを開いて問題が再現したときに、コマンドパレットから `Developer: Open Webview Developer Tools` を実行してエラーメッセージ等が出ていないか確認していただけると助かります。
エラーメッセージが出ている場合はポップアップした Developer Tools の `Console` タブに出ているはずです。

![image](https://user-images.githubusercontent.com/1239141/117151169-c6dd9280-adf3-11eb-81f2-2b5c643f6fce.png)

**Comment by susumuota** [comment]
@negokaz ありがとうございます。

まず、プレビューが問題なく表示される時と、真っ白になる時があり、今のところ再現する条件はよくわかりません。昨日2, 3回試した時は毎回真っ白になる現象が起きていました。先程試したところ、数回に1度、真っ白になる状態が再現されました。

取り急ぎ、プレビューが真っ白になった時のログをお送りします。

```
[Extension Host] zenn-editor is now active (at t.activate (/Users/ota/.vscode-insiders/extensions/negokaz.zenn-editor-0.7.1/dist/extension.js:2:58776))
console.ts:137 [Extension Host] Local proxy server started on http://127.0.0.1:50969 (at Server.<anonymous> (/Users/ota/.vscode-insiders/extensions/negokaz.zenn-editor-0.7.1/dist/extension.js:2:106030))
log.ts:296   ERR connect ECONNREFUSED 127.0.0.1:50970: Error: connect ECONNREFUSED 127.0.0.1:50970
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
console.ts:137 [Extension Host] 👀Preview on http://localhost:50970 (at Socket.<anonymous> (/Users/ota/.vscode-insiders/extensions/negokaz.zenn-editor-0.7.1/dist/extension.js:2:104805))
webviewCommands.ts:38 Using standard dev tools to debug iframe based webview
```

また、この時、ブラウザで http://localhost:50970 と http://localhost:50969 にアクセスしてみましたが、両方ともプレビューが表示されました。

スクリーンショットはこんな感じです。

![image](https://user-images.githubusercontent.com/1632335/117155344-aa435980-adf7-11eb-9766-dfd493bf94e6.png)

**Comment by negokaz** [comment]
@susumuota 確認ありがとうございます。私の環境で VSCode Insiders をインストールすると、問題が再現しました。Console を確認すると同様に次のエラーが出力されていました。

```
  ERR connect ECONNREFUSED 127.0.0.1:65183: Error: connect ECONNREFUSED 127.0.0.1:65183
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

このエラーのあとに `zenn preview` のログ `👀Preview on http://localhost:xxxx` が出力されているので、プレビューが完全に起動しきる前に Webview がプレビューのポートにアクセスしまっているような気がします。`zenn preview` がログを出力した後（プレビューの起動が確認できた後）に Webview がプレビューのポートにアクセスしにいくよう調整してみます。

**Comment by negokaz** [comment]
@susumuota 問題を修正したバージョン [`0.7.2`](https://github.com/negokaz/vscode-zenn-editor/blob/main/CHANGELOG.md#072---2021-05-09) をリリースしました！

バージョンアップして問題が解消しているかご確認いただけるとありがたいです。

**Comment by susumuota** [comment]
@negokaz ありがとうございます！  以下バージョンの VSCode - Insiders にて `0.7.2` をインストールしてテストしたところ、問題なくプレビューが表示されることを確認しました。

```
Version: 1.57.0-insider (Universal)
Commit: a19565da7dfc739fa26e36aae96113e19fe3806f
Date: 2021-05-07T18:11:54.098Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0
```
