### ISSUE TITLE
WSL 2 + Ubuntu 20.04 LTS でプレビューが真っ白になる

### ISSUE THREAD

**Issue by xeres** [negokaz/vscode-zenn-editor#25]

**Comment by xeres** [comment]
すいません、操作ミスでケースのタイトルがおかしくなってしまいました。

WSL 2 + Ubuntu 20.04 LTS の環境で、スクリーンショットの通り、プレビューがうまく表示できない症状が出ています。

![Network+Console-1](https://user-images.githubusercontent.com/294146/117385297-c8a47480-af1f-11eb-828b-35b397f3e938.png)
![Network+Console-2](https://user-images.githubusercontent.com/294146/117385304-cb9f6500-af1f-11eb-9181-068ee2621cc5.png)

- 環境
    - Windows 10 20H2 (19042.928)
    - VS Code 1.56.0
    - Zenn Editor 0.7.1
    - node v14.16.1
    - npm/npx 6.14.12
    - zenn-cli v0.1.79

状況を見ると、プレビュー用の Proxy と正常に通信ができていないようです。

```shell-session
> ss -l -t -4
State                   Recv-Q                   Send-Q                                     Local Address:Port                                     Peer Address:Port                   Process
> ss -l -t -6
State                    Recv-Q                   Send-Q                                     Local Address:Port                                      Peer Address:Port                  Process
LISTEN                   0                        511                                                    *:39301                                                *:*
LISTEN                   0                        511                                                    *:41959                                                *:*
LISTEN                   0                        511                                                    *:40113                                                *:*
> curl http://127.0.0.1:39301/__vscode_zenn_editor_preview_proxy_index/articles/2021-04-30-lets-use-aws-sso-util

            <html>
                <head>
                    <script src="/__vscode_zenn_editor_preview_proxy_index/proxyView.js"></script>
                </head>
                <body>
                    <div>
                        <iframe id="zenn" src="/articles/2021-04-30-lets-use-aws-sso-util" width="100%" height="100%" seamless frameborder=0></iframe>
                    </div>
                </body>
            </html>
        %
> curl http://127.0.0.1:39301/articles/2021-04-30-lets-use-aws-sso-util
curl: (7) Failed to connect to 127.0.0.1 port 39301: Connection refused
> curl http://localhost:39301/articles/2021-04-30-lets-use-aws-sso-util
curl: (7) Failed to connect to localhost port 39301: Connection refused
> curl 'http://[::1]:39301/articles/2021-04-30-lets-use-aws-sso-util'
curl: (7) Failed to connect to ::1 port 39301: Connection refused
> curl 'http://ip6-localhost:39301/articles/2021-04-30-lets-use-aws-sso-util'
curl: (7) Failed to connect to ip6-localhost port 39301: Connection refused
```

WSL 2 は localhost 周りの挙動が特殊なので、その影響かもしれません。
参考URL: https://yanor.net/wiki/?Windows/WSL/%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF/WSL2%E3%81%AELinux%E3%81%AB127.0.0.1%E3%81%A7%E6%8E%A5%E7%B6%9A%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84

同じディストリビューションを WSL 1 に変換したところ、問題なく表示されました。

**Comment by negokaz** [comment]
@xeres 問題のご報告ありがとうございます。
詳しく検証までして頂き、とても助かります。

検証いただいた内容を見ると、Proxy（`http://127.0.0.1:39301/__vscode_zenn_editor_preview_proxy_index/...`）へのアクセスは成功しているが、Proxy から `zenn preview` へのリクエストの転送（`http://127.0.0.1:39301/articles/...`）に失敗しているというふうに見えますね。

WSL 2 上で、`zenn preview` のページに直接アクセスした場合はリクエストが成功するでしょうか？
Console で次のように `zenn preview` のページにアクセスするための URL が表示されます。
```
👀Preview on http://localhost:40113
```

※ この URL のポート番号は都度変化します

**Comment by xeres** [comment]
@negokaz 
レスありがとうございます。

> 👀Preview on http://localhost:XXXXX

こちらの  `zen preview` で起動されているサーバーの方は元々 `curl` のリクエストに成功していました。
何度か追試をしていますが、引き続き問題なくリクエストに成功しています。

> Local proxy server started on http://127.0.0.1:XXXXX

こちらは、同じ環境で何度か追試をしてみたところ、何故か `curl` のリクエストに成功するようになってしましました。
逆に、`curl` で `Connection refused` になるケースが再現できなくなってしまいました…。

一方で、引き続き VS Code の Zenn Editor Preview によるアクセスは `net::ERR_CONNECTION_REFUSED` になりますので、
起きている事象がなんだかチグハグな感じがしています。

単純に Proxy が起動する前にアクセスしようとしてコネクションが張れていないのかな、とも推察したのですが、
Developer Tools で Zenn Preview Editor の WebView だけ (もしくは iframe だけ) 再読み込みさせることは可能でしょうか。
VS Code 拡張の開発に不慣れで、色々探してみたのですが見つからず…。

**Comment by negokaz** [comment]
@xeres 確認頂きありがとうございます。

時々で振る舞いが変わるのは厄介ですね…

> Developer Tools で Zenn Preview Editor の WebView だけ (もしくは iframe だけ) 再読み込みさせることは可能でしょうか。

次を試して頂けますでしょうか。

Developer Tools の Elements から `id="zenn-proxy"` の iframe を探して選択します。
iframe の `src=` に設定されている URL をコピーします。

![image](https://user-images.githubusercontent.com/1239141/117531300-d8ee4980-b01c-11eb-9b35-ddca9f127398.png)

Console から次のスニペットを実行します。
すると、同じページに遷移して、再読み込みと同じ状態になるはずです。

```javascript
$('#zenn-proxy').contentWindow.location.replace('{iframe の src からコピーした URL を指定}')
```

このときに、iframe の Element （もしくはその iframe が所属する frame の element）が選択されていないと、Element が見つからずスニペットの実行がエラーになるので注意してください。

**Comment by negokaz** [comment]
@xeres バージョン [`0.7.2`](https://github.com/negokaz/vscode-zenn-editor/blob/main/CHANGELOG.md#072---2021-05-09) で Webview がプロキシにアクセスするタイミングを調整しました。

Webview がアクセスするタイミングが早すぎるのが原因だとすると問題が改善しているかもしれないので、ご確認いただけると幸いです。

**Comment by xeres** [comment]
@negokaz ご連絡ありがとうございます。

`0.7.2` で無事にプレビューが表示できるのを確認しました。
再読み込みを試す前に修正していただいてありがとうございました！！！

**Comment by negokaz** [comment]
@xeres 問題が解消して良かったです！
調査にご協力頂きありがとうございました！
