### ISSUE TITLE
Windows10でPreviewが表示されない

### ISSUE THREAD

**Issue by tsubakisakura** [negokaz/vscode-zenn-editor#30]
こんにちは。
Zenn Editorのプラグインをセットアップしてみたのですが、プレビューが表示できず、どうしたものかと思ってご質問させて頂きます。

概ね [Windows10上にZennの執筆環境を構築する](https://zenn.dev/nkys39/articles/struct-zenn-win10) の手順の通りにセットアップしたと思います。
ここでexample1.mdのpreviewを表示しようと思ったのですが、こちらのような画面になってしまいました。
![error](https://user-images.githubusercontent.com/93580434/147852354-0cf9f6d6-7683-45d0-97d0-1cbb4f4e1b76.png)

拡張機能のログに何か残っていないかと思って見ていたのですが、VSCodeの出力パネルで「拡張機能」とか「ログ(拡張機能ホスト)」を選択しても特にそれっぽいログは今のところ見つかっていません。
これとは別に、VSCodeのプロンプトから直接 ```npx zenn preview``` として表示される ```http://localhost:8000``` に対してブラウザでアクセスすると、こちらは特に問題なくプレビューできています。

このような状況から考えられそうな問題を検索してみたのですが、関連していそうな記事が自分では見つけられていません。こうしたら糸口が掴めそう、といった何かがありましたらご教授頂けると嬉しいです。

なお、VSCodeのバージョン情報はこちらです。

* バージョン: 1.63.2 (user setup)
* コミット: 899d46d82c4c95423fb7e10e68eba52050e30ba3
*  日付: 2021-12-15T09:40:02.816Z (2 週間前)
* Electron: 13.5.2
* Chromium: 91.0.4472.164
* Node.js: 14.16.0
* V8: 9.1.269.39-electron.0
* OS: Windows_NT x64 10.0.19043

これとは別にWindowsにインストールしたNode.jsのバージョンは 16.13.1 です。

**Comment by negokaz** [comment]
@tsubakisakura 問題のご報告ありがとうございます。
ログの確認などいくつか調査もして頂いたようで助かります。

お手数ですが、ご利用中の zenn-cli のバージョンをご教示頂いてもよろしいでしょうか？
拡張機能側では `npx` は利用していないため、グローバルか、プロジェクト（`zenn-docs`）内に zenn-cli がインストールされていると思います。zenn-cli のバージョンは次のオプションで確認できます。

```
zenn --version
```

**Comment by tsubakisakura** [comment]
@negokaz さん
ご返事ありがとうございます！
確かにプロジェクト内の ```zenn-docs\node_modules\zenn-cli``` にインストールされており ```npx zenn --version``` だと次のように出力されておりました。

~~~
0.1.100
~~~

と、この確認方法で問題なかったでしょうか。```拡張機能側ではnpxを利用していない``` というのが気になりましたがnpx経由以外で起動する方法が分からず…申し訳ありません。

**Comment by tsubakisakura** [comment]
調べてるうちに ```node_modules\.bin\zenn.ps1``` というスクリプトがあることに気づき、これを実行できるようにすれば良いのでは？と思いつつ [Qiita: VSCode のターミナルで PATH 自動設定](https://qiita.com/mysticatea/items/063b1a5ce5f49eb12cd2) の通りに ```settings.js``` を更新しました。
その後VSCodeのターミナルから次のコマンドを実行してバージョンを取得できるようになりました。

~~~
PS K:\home\tsubaki\zenn-docs> zenn --version
0.1.100
~~~

が、現状まだ表示はされておりません。

エクスプローラーパネルで ```example1.md``` などのファイルを選択するたびに ```ログ(拡張機能ホスト)``` に次のようなログが出ることは分かってきました。(もしかするとこのログは以前の状態でも出ていたかもしれません。あまり自信がなくて申し訳ありません)

~~~
2022-01-04 23:40:36.535] [exthost] [error] Error: Cannot resolve tree item for element 0/0:books
	at c:\Users\tsubaki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:63223
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
~~~

**Comment by negokaz** [comment]
@tsubakisakura 
バージョンをお調べ頂きありがとうございます。
同じバージョンの zenn-cli を使うと私の環境でも問題が再現しました。
zenn-cli のバージョンアップにより、プレビュー時の URL の形式が変わったのが原因でした。
拡張側で新しい URL の形式をサポートする必要があります。
修正に取り掛かろうと思います。

調査の中で zenn-cli のバージョンを `0.1.81` にダウングレードすると一時的に問題を回避できることもわかりました。
修正が完了するまでは zenn-cli のプレビュー機能をブラウザからご利用いただくか、一時的に zenn-cli をダウングレードするとプレビューを利用頂けるはずです。
ただし、ダウングレードするとうまく表示できない要素が出てきたり、記事を執筆する上で何らかの制約を受ける可能性があるため、現在のバージョンのままブラウザからプレビュー機能をご利用いただくのが良さそうに思います。

**Comment by tsubakisakura** [comment]
@negokaz さん
ご返信遅くなってしまい申し訳ありません。
再現＆原因まで見つかったようで良かったです！
また、対処法についても調べて頂きまして、ありがとうございます。
暫くは、ブラウザのプレビュー機能を利用させて頂こうと思います。

**Comment by negokaz** [comment]
@tsubakisakura 

先ほど新しいバージョンをリリースしました。
新しいバージョンでプレビューを試してみて頂けますか？

新しいバージョンの変更内容は次のページをご参照ください。

> 0.9.0 - 2022-01-22
>
> [vscode-zenn-editor/CHANGELOG.md at main · negokaz/vscode-zenn-editor](https://github.com/negokaz/vscode-zenn-editor/blob/main/CHANGELOG.md#%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E4%BA%88%E5%AE%9A)

**Comment by tsubakisakura** [comment]
折角ご対応頂いたところご返信大変遅くなって申し訳ありません！
最新のバージョンをインストールすることで私の環境でもプレビューが表示されるようになりました。
大変ありがとうございました。こちら閉じさせて頂きます。
