### ISSUE TITLE
preview が表示されない

### ISSUE THREAD

**Issue by Jxck** [negokaz/vscode-zenn-editor#31]
以下の book を preview 表示するとエラーが出ました。

![image](https://user-images.githubusercontent.com/322289/149788159-50d15762-2da0-4649-babc-a371835302fa.png)

エラーは以下です。

![image](https://user-images.githubusercontent.com/322289/149788102-3702cd4e-b371-48d8-b44f-2c5a58fe23de.png)

devtools で見ると、 proxy は起動しているが 404 になっています。

![image](https://user-images.githubusercontent.com/322289/149788394-4c98ffa4-ca04-45fb-b4e0-f070c706d13c.png)

`0.readme.md` のようなファイル名は、 zenn-cli 上は以下のような URL としてエスケープが必要なようです。

http://localhost:65430/books/origin-anatomia/0%252Ereadme%252Emd

ただ、なんというか、、 "%252E" は "." を "%2E" に変換してさらに "%252E" にしているので、なんでそんなことしているのだろう?という気もします(エスケープするにも一回で良いような気が)。なので、 zenn-cli とこちら、どっちの issue かは悩みました。が、一応エラーになってるのはこちらなので、こちらに立てます。

cc @catnose99 もしなんかコメントあったらお願いします。

**Comment by negokaz** [comment]
@Jxck 
問題のご報告と調査ありがとうございます！
zenn-cli のバージョンアップにより book のチャプターを表示する URL が変わったようですね。
URL のエンコード形式は少し気になりますが、とりあえず拡張機能が正しい URL を表示できるように修正しようと思います。

**Comment by negokaz** [comment]
@Jxck 

先ほど新しい URL のエンコード形式に対応したバージョンをリリースしました。
こちらでも動作確認しておりますが、問題が解消しておりましたらご一報頂けますと幸いです！

リリース内容の詳細は次のページをご参照ください。

> 0.9.0 - 2022-01-22
>
> [vscode-zenn-editor/CHANGELOG.md at main · negokaz/vscode-zenn-editor](https://github.com/negokaz/vscode-zenn-editor/blob/main/CHANGELOG.md#%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E4%BA%88%E5%AE%9A)

**Comment by Jxck** [comment]
@negokaz 見れました! ありがとうございました!
