### ISSUE TITLE
VSCode内記事プレビュー表示不具合(サイズ不良)

### ISSUE THREAD

**Issue by haoblackj** [negokaz/vscode-zenn-editor#34]
いつも便利に使わせていただいております。
ありがとうございます。

掲題の件について、下記ご報告いたします。

## 事象
articlesフォルダ内の記事を開いた状態で、以下の事象が起こります。

- Markdownファイルを開いた状態で右上のボタンから実行すると、プレビュー画面が小さく表示されてしまう(![zenn-editor-preview-bug20221118](https://user-images.githubusercontent.com/17177994/202590845-39a8575c-2647-4381-baa7-92a2dcee79bf.gif))
- コマンドパレットから「Zenn Editor: Open Preview」を実行しても、プレビュー画面が表示されない。(![zenn-editor-preview-bug20221118-2](https://user-images.githubusercontent.com/17177994/202590945-27efab42-5d7c-4f39-b0b7-b133cf0564c0.gif))

## 実行環境
以下のとおりです。

### Zenn Editor
> v0.9.0

### VSCode

> バージョン: 1.73.0 (system setup)
> コミット: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
>  日付: 2022-11-01T15:34:06.111Z
> Electron: 19.0.17
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Windows_NT x64 10.0.19044
> Sandboxed: No

### その他
> Zenn-CLI 0.1.132

以上となります。
お忙しいところとは存じますが、何卒ご対応のほどよろしくお願いいたします。

**Comment by negokaz** [comment]
@haoblackj 

不具合のご報告ありがとうございます！

「コマンドパレットから「Zenn Editor: Open Preview」を実行しても、プレビュー画面が表示されない。」は私の環境でも再現され、調査したところ実装に不具合がありました。

「Markdownファイルを開いた状態で右上のボタンから実行すると、プレビュー画面が小さく表示されてしまう」の原因を詳しく調査させて頂きたいです。

私の環境では事象を再現できなかったので、お手数ですが以下の手順で表示要素のサイズを確認いただけますでしょうか。

1. プレビューを開いた状態で「Webview 開発者ツールを開く」
    ![image](https://user-images.githubusercontent.com/1239141/202880951-04522b8a-3deb-4185-abfc-7e079e6f3ef9.png)
2. 開発者ツールで以下の要素のサイズを確認（Ctrl + F で以下のセレクタを入力し、見つかった要素をクリックします）
     - `iframe#active-frame`
     - `iframe#zenn`
     - `iframe#zenn-proxy`
     ![image](https://user-images.githubusercontent.com/1239141/202880979-90f26cb9-ce9a-4d04-bb31-a5438d392a37.png)
     上記画像で `220×1145.600` となっているの部分が要素のサイズです。
     正常だと `iframe#zenn` と `iframe#zenn-proxy` が `iframe#active-frame` とほぼ同じサイズになっているはずなのですが、恐らく一部の要素のサイズが正しいサイズになっていないのではないかと予想しています。

**Comment by haoblackj** [comment]
@negokaz 
お世話になります。

表示要素のサイズについて、採取しましたので共有します。

### iframe#active-frame
![active-frame](https://user-images.githubusercontent.com/17177994/202883271-2a519b96-871f-4bc7-9cca-2bb0404afac8.png)

### iframe#zenn
![zenn](https://user-images.githubusercontent.com/17177994/202883286-ae58a426-ee76-49d2-874d-20ffe70e69bf.png)

### iframe#zenn-proxy
![zenn-proxy](https://user-images.githubusercontent.com/17177994/202883293-d65c8fdd-af75-4105-8b18-11d98ff1fdb3.png)

予想されていたとおり、 zenn-proxy の要素のサイズが小さくなっているようです。
(他2つのサイズが 508×697 であるところ、 zenn-proxy のみ 468×150 となっています)

以上となります。
何卒よろしくお願いいたします。

**Comment by negokaz** [comment]
@haoblackj ご確認ありがとうございます。

`iframe#zenn` について、選択されている要素が `iframe#active-frame` になっているようにも見えるのですが、問題なさそうでしょうか？

**Comment by negokaz** [comment]
@haoblackj 

立て続けに申し訳ございません。

`iframe#zenn-proxy` の Computed で、`height` と `width` を展開した状態がどのようになっているかも確認させて頂きたいです。

![image](https://user-images.githubusercontent.com/1239141/202886300-bf3c7cf0-4abb-4009-88bf-e27ec3106542.png)

**Comment by haoblackj** [comment]
@negokaz 
お世話になります。

失礼しました。
zenn のサイズは zenn-proxyとほぼ同じだったようです。
あらためてスクリーンショットを添付いたします。
![zenn](https://user-images.githubusercontent.com/17177994/202890341-32bde6e5-760f-4e67-bd7a-d526515fae23.png)

また、 zenn-proxy の height と width も添付いたします。
![zenn-proxy-height-width](https://user-images.githubusercontent.com/17177994/202890359-c4465239-5181-4022-a422-58bf48d3555e.png)

展開したところ、双方とも 100% と記載されておりました。

以上となります。
何卒よろしくお願いいたします。

**Comment by negokaz** [comment]
@haoblackj 

ご確認ありがとうございます。
どちらも想定通りの状態になっているようです。

zenn-proxy（及び zenn）は `height="100%"` によって親要素いっぱいの高さに広がる想定なのですが、なぜか 150px に縮小してしまっているようです。

zenn-proxy の親要素のどこかで 150px の高さになっている箇所がないか確認頂くことは可能でしょうか？

**Comment by haoblackj** [comment]
@negokaz 

お世話になります。

zenn-proxy の親になっている html にて height が 153.333px になっておりました。
スクリーンショットをお送りします。
![image](https://user-images.githubusercontent.com/17177994/205496802-68cba812-4b8d-4516-92f5-e026c900665c.png)

他に採取すべき情報などはありますでしょうか?

**Comment by negokaz** [comment]
@haoblackj 

私の環境ですと、zenn-proxy の親の html の `height` に `100%` が指定されていました。これは [full-page-iframe.css](https://github.com/negokaz/vscode-zenn-editor/blob/c142a3e4a3c87d609434291d3541fc430be518c0/src/webview/full-page-iframe.css) によって指定された値です。

![image](https://user-images.githubusercontent.com/1239141/205628775-87451a4a-0307-4899-9fa8-a3f2b1eeb000.png)

`zenn-proxy` がある html のヘッダに webview.js と、以下のような style は定義されているでしょうか？

![image](https://user-images.githubusercontent.com/1239141/206854742-0da0032f-f22e-4dff-acba-6beff811085c.png)

また、Developer Tool の Console にエラーが出ていないかをご確認頂きたいです。

**Comment by haoblackj** [comment]
@negokaz 
お世話になります。

`zenn-proxy`がある html のヘッダには、画像のような style は定義されていないように思われます。
スクリーンショットを添付いたします。
![image](https://user-images.githubusercontent.com/17177994/206857101-0003a68a-6981-4fff-a812-4c45698f201b.png)


また、Console についても添付のようなエラーがありました。
![image](https://user-images.githubusercontent.com/17177994/206857127-727fa59c-5c9c-4792-a714-f5c25b923c4b.png)


何卒よろしくお願いいたします。

**Comment by negokaz** [comment]
@haoblackj 
ご確認ありがとうございます。

`webview.js` がうまく読み込めていないかもしれません。

`webview.js` の URL 中に `/home/node/.vscode-server/` というパスがあるように見受けられますが、こちら devcontainer を利用されているでしょうか？

**Comment by haoblackj** [comment]
@negokaz 

お世話になります。

はい、devcontainerを使用しております。

**Comment by h-takesg** [comment]
@negokaz 
私もdevcontainerにて同様の事象を確認しました．
Networkを確認したところ`webview.js`のGETに401が返ってきているようです．
![image](https://user-images.githubusercontent.com/82633007/220535969-b71835bc-3b19-4db5-91a4-765424ef18a1.png)

**Comment by negokaz** [comment]
@haoblackj @h-takesg 

お待たせしました！
先ほどリリースした 0.9.1 にて Devcontainer 環境でプレビューが表示されない問題が解消できていると思います。
ひとまず本 issue はクローズさせて頂きます。
問題が解消されていない場合はお知らせいただけると幸いです。
