### ISSUE TITLE
表示ファイルを切り替えるとサイドバーが勝手に開いてしまう

### ISSUE THREAD

**Issue by book000** [negokaz/vscode-zenn-editor#35]
こんにちは、素晴らしい拡張機能を開発していただきありがとうございます。
バグなのか仕様なのか悩ましいのですが、表題のような挙動を確認しましたので報告いたします。

## 環境

- Windows 10 22H2 (Build 19045.2604)
- Visual Studio Code 1.76.0 (user setup)
- Zenn Editor v0.9.0
- 再現確認のために Windows Sandbox 内でも検証して再現しました。

## 再現手順

Visual Studio Code と Node.js をインストールし、VS Code に Zenn Editor 拡張機能をインストールしています。  
ファイルを開いたときに新規タブで必ず開くよう、VS Code 設定で `"workbench.editor.enablePreview": false` を設定しています。

1. Explorer タブを開き、`ZENN CONTENTS` セクションが使えるようにします。（🔄を押してタイトルが表示されるようにしています）
2. 複数の Markdown ファイルを開きます。
3. Explorer タブを閉じます。
4. 今開いているファイルタブと別のファイルタブを開きます。
5. 勝手に Explorer タブが開きます。

以上を実施した動画を用意しました。

https://user-images.githubusercontent.com/8929706/222684085-aae0cf25-637d-4667-a0cd-ea1a5004b7cf.mp4

（すみません、`zenn-cli` をインストールし忘れていますがインストールしていても挙動は変わりません）

## 期待する動作

ノートパソコンなど小さい画面で作業している際、サイドバーが表示されていると邪魔なので閉じるようにしています。
また、記事を書いているときに他の記事を参考にしたりするので、この時に勝手に開いて再度閉じるのが少し億劫に感じます。
可能であれば、**ファイルタブを切り替えたときにサイドバー（エクスプローラータブ）が開かない** ような動作を期待します。

## 備考

VS Code 側の設定で以下画像のように Zenn Contents セクションを表示しないようにしてもファイル切り替えで再度有効化されてしまうのも気になっています。ファイルタブ切り替え時に Zenn Contents セクションの初期化処理が行われているのでしょうか？

![image](https://user-images.githubusercontent.com/8929706/222685646-6a243135-fb4f-4b55-a5a3-363337e58b41.png)

よろしくお願いいたします。

**Comment by negokaz** [comment]
@book000 

フィードバックありがとうございます！
こちらでも事象が再現できました。

#37 にて解決を試みています。
修正版がリリースできましたら、改めてお知らせいたします。

**Comment by negokaz** [comment]
@book000 

お待たせしました！
先ほどサイドバーが勝手に開く問題を解消した 0.9.1 をリリースしました。
ひとまず本 issue はクローズさせて頂きます。
問題が解消できていない場合はお知らせいただけると助かります。
