### ISSUE TITLE
プレビュー上のリンクカードにマウスホバーするとエディタ側のフォーカスが外れる

### ISSUE THREAD

**Issue by liveasnotes** [negokaz/vscode-zenn-editor#40]
プレビュー対象が自動で切り替わって便利なので今も使わせていただいています。

表題の通り、プレビュー上のリンクカードにマウスホバーした際、エディタ側のフォーカスが外れる現象を確認しました。

手が触れるなどしてマウスが動くことで、mdファイルの編集中に入力を受け付けなくなることがありました。
再現条件が分かったので、こちらで共有させていただきます。

ご対応のほど、ご検討いただければ幸いです。

環境：
Windows 10
VS Code 1.89.0

**Comment by negokaz** [comment]
@liveasnotes 事象のご報告ありがとうございます！

以下の環境で再現を試みましたが、私の環境では再現できませんでした。。

- Windows 11
-  VS Code: 1.89.1
- zenn-cli: 0.1.153

VS Code のコマンドパレットから Webview 開発者ツールを開いて、マウスホバー時にエラー等が出力されていないかご確認いただくことは可能でしょうか？

**Comment by negokaz** [comment]
問題が再現できないため issue をクローズさせていただきます。
追加情報があれば、お手数ですが issue の再オープンをお願いします。
