### ISSUE TITLE
article を作成しようとすると spawn EINVAL エラーが発生する

### ISSUE THREAD

**Issue by finou882** [negokaz/vscode-zenn-editor#41]
Error running command zenn-editor.create-new-article: A system error occurred (spawn EINVAL). This is likely caused by the extension that contributes zenn-editor.create-new-article.

**Comment by finou882** [comment]
このようなエラーが出てarticleを作成できません。
必要な情報等あれば適宜提供します。

**Comment by negokaz** [comment]
NodeJS のセキュリティ脆弱性への対策によって、Windows 環境で破壊的変更が入った影響のようです。

関連事項：
- https://github.com/nodejs/node/issues/52554
- [VSCodeエディタ内でprettierが動かなくなった #VSCode - Qiita](https://qiita.com/pilot/items/7b1ed2a3708e6c61cfc6)

**Comment by negokaz** [comment]
@finou882 
先ほど `0.9.2` をリリースしました。
エラーが解消しているかご確認いただけますでしょうか？

**Comment by finou882** [comment]
返信が遅れて申し訳ございません。
エラーが解消されました！
ありがとうございます。
